package com.dao;

import java.util.List;

import com.model.TNdcreceived;

public interface TNdcreceivedMapperExt {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    List<TNdcreceived> selectByExample();
}