package com.dao;

import com.model.TNdcreceived;
import com.model.TNdcreceivedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TNdcreceivedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int countByExample(TNdcreceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int deleteByExample(TNdcreceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int insert(TNdcreceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int insertSelective(TNdcreceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    List<TNdcreceived> selectByExample(TNdcreceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    TNdcreceived selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int updateByExampleSelective(@Param("record") TNdcreceived record, @Param("example") TNdcreceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int updateByExample(@Param("record") TNdcreceived record, @Param("example") TNdcreceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int updateByPrimaryKeySelective(TNdcreceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    int updateByPrimaryKey(TNdcreceived record);
}