package com.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TNdcreceivedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public TNdcreceivedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOidIsNull() {
            addCriterion("OID is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("OID is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(String value) {
            addCriterion("OID =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(String value) {
            addCriterion("OID <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(String value) {
            addCriterion("OID >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(String value) {
            addCriterion("OID >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(String value) {
            addCriterion("OID <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(String value) {
            addCriterion("OID <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLike(String value) {
            addCriterion("OID like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotLike(String value) {
            addCriterion("OID not like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<String> values) {
            addCriterion("OID in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<String> values) {
            addCriterion("OID not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(String value1, String value2) {
            addCriterion("OID between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(String value1, String value2) {
            addCriterion("OID not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andFramenoIsNull() {
            addCriterion("FRAMENO is null");
            return (Criteria) this;
        }

        public Criteria andFramenoIsNotNull() {
            addCriterion("FRAMENO is not null");
            return (Criteria) this;
        }

        public Criteria andFramenoEqualTo(String value) {
            addCriterion("FRAMENO =", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoNotEqualTo(String value) {
            addCriterion("FRAMENO <>", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoGreaterThan(String value) {
            addCriterion("FRAMENO >", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoGreaterThanOrEqualTo(String value) {
            addCriterion("FRAMENO >=", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoLessThan(String value) {
            addCriterion("FRAMENO <", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoLessThanOrEqualTo(String value) {
            addCriterion("FRAMENO <=", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoLike(String value) {
            addCriterion("FRAMENO like", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoNotLike(String value) {
            addCriterion("FRAMENO not like", value, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoIn(List<String> values) {
            addCriterion("FRAMENO in", values, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoNotIn(List<String> values) {
            addCriterion("FRAMENO not in", values, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoBetween(String value1, String value2) {
            addCriterion("FRAMENO between", value1, value2, "frameno");
            return (Criteria) this;
        }

        public Criteria andFramenoNotBetween(String value1, String value2) {
            addCriterion("FRAMENO not between", value1, value2, "frameno");
            return (Criteria) this;
        }

        public Criteria andEnginenoIsNull() {
            addCriterion("ENGINENO is null");
            return (Criteria) this;
        }

        public Criteria andEnginenoIsNotNull() {
            addCriterion("ENGINENO is not null");
            return (Criteria) this;
        }

        public Criteria andEnginenoEqualTo(String value) {
            addCriterion("ENGINENO =", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoNotEqualTo(String value) {
            addCriterion("ENGINENO <>", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoGreaterThan(String value) {
            addCriterion("ENGINENO >", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoGreaterThanOrEqualTo(String value) {
            addCriterion("ENGINENO >=", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoLessThan(String value) {
            addCriterion("ENGINENO <", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoLessThanOrEqualTo(String value) {
            addCriterion("ENGINENO <=", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoLike(String value) {
            addCriterion("ENGINENO like", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoNotLike(String value) {
            addCriterion("ENGINENO not like", value, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoIn(List<String> values) {
            addCriterion("ENGINENO in", values, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoNotIn(List<String> values) {
            addCriterion("ENGINENO not in", values, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoBetween(String value1, String value2) {
            addCriterion("ENGINENO between", value1, value2, "engineno");
            return (Criteria) this;
        }

        public Criteria andEnginenoNotBetween(String value1, String value2) {
            addCriterion("ENGINENO not between", value1, value2, "engineno");
            return (Criteria) this;
        }

        public Criteria andInspectionresultIsNull() {
            addCriterion("INSPECTIONRESULT is null");
            return (Criteria) this;
        }

        public Criteria andInspectionresultIsNotNull() {
            addCriterion("INSPECTIONRESULT is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionresultEqualTo(String value) {
            addCriterion("INSPECTIONRESULT =", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultNotEqualTo(String value) {
            addCriterion("INSPECTIONRESULT <>", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultGreaterThan(String value) {
            addCriterion("INSPECTIONRESULT >", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTIONRESULT >=", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultLessThan(String value) {
            addCriterion("INSPECTIONRESULT <", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultLessThanOrEqualTo(String value) {
            addCriterion("INSPECTIONRESULT <=", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultLike(String value) {
            addCriterion("INSPECTIONRESULT like", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultNotLike(String value) {
            addCriterion("INSPECTIONRESULT not like", value, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultIn(List<String> values) {
            addCriterion("INSPECTIONRESULT in", values, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultNotIn(List<String> values) {
            addCriterion("INSPECTIONRESULT not in", values, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultBetween(String value1, String value2) {
            addCriterion("INSPECTIONRESULT between", value1, value2, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andInspectionresultNotBetween(String value1, String value2) {
            addCriterion("INSPECTIONRESULT not between", value1, value2, "inspectionresult");
            return (Criteria) this;
        }

        public Criteria andIsexportIsNull() {
            addCriterion("ISEXPORT is null");
            return (Criteria) this;
        }

        public Criteria andIsexportIsNotNull() {
            addCriterion("ISEXPORT is not null");
            return (Criteria) this;
        }

        public Criteria andIsexportEqualTo(String value) {
            addCriterion("ISEXPORT =", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportNotEqualTo(String value) {
            addCriterion("ISEXPORT <>", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportGreaterThan(String value) {
            addCriterion("ISEXPORT >", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportGreaterThanOrEqualTo(String value) {
            addCriterion("ISEXPORT >=", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportLessThan(String value) {
            addCriterion("ISEXPORT <", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportLessThanOrEqualTo(String value) {
            addCriterion("ISEXPORT <=", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportLike(String value) {
            addCriterion("ISEXPORT like", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportNotLike(String value) {
            addCriterion("ISEXPORT not like", value, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportIn(List<String> values) {
            addCriterion("ISEXPORT in", values, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportNotIn(List<String> values) {
            addCriterion("ISEXPORT not in", values, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportBetween(String value1, String value2) {
            addCriterion("ISEXPORT between", value1, value2, "isexport");
            return (Criteria) this;
        }

        public Criteria andIsexportNotBetween(String value1, String value2) {
            addCriterion("ISEXPORT not between", value1, value2, "isexport");
            return (Criteria) this;
        }

        public Criteria andFactorycolorIsNull() {
            addCriterion("FACTORYCOLOR is null");
            return (Criteria) this;
        }

        public Criteria andFactorycolorIsNotNull() {
            addCriterion("FACTORYCOLOR is not null");
            return (Criteria) this;
        }

        public Criteria andFactorycolorEqualTo(String value) {
            addCriterion("FACTORYCOLOR =", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorNotEqualTo(String value) {
            addCriterion("FACTORYCOLOR <>", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorGreaterThan(String value) {
            addCriterion("FACTORYCOLOR >", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorGreaterThanOrEqualTo(String value) {
            addCriterion("FACTORYCOLOR >=", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorLessThan(String value) {
            addCriterion("FACTORYCOLOR <", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorLessThanOrEqualTo(String value) {
            addCriterion("FACTORYCOLOR <=", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorLike(String value) {
            addCriterion("FACTORYCOLOR like", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorNotLike(String value) {
            addCriterion("FACTORYCOLOR not like", value, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorIn(List<String> values) {
            addCriterion("FACTORYCOLOR in", values, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorNotIn(List<String> values) {
            addCriterion("FACTORYCOLOR not in", values, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorBetween(String value1, String value2) {
            addCriterion("FACTORYCOLOR between", value1, value2, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andFactorycolorNotBetween(String value1, String value2) {
            addCriterion("FACTORYCOLOR not between", value1, value2, "factorycolor");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionIsNull() {
            addCriterion("COLORCODEDESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionIsNotNull() {
            addCriterion("COLORCODEDESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionEqualTo(String value) {
            addCriterion("COLORCODEDESCRIPTION =", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionNotEqualTo(String value) {
            addCriterion("COLORCODEDESCRIPTION <>", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionGreaterThan(String value) {
            addCriterion("COLORCODEDESCRIPTION >", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("COLORCODEDESCRIPTION >=", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionLessThan(String value) {
            addCriterion("COLORCODEDESCRIPTION <", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionLessThanOrEqualTo(String value) {
            addCriterion("COLORCODEDESCRIPTION <=", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionLike(String value) {
            addCriterion("COLORCODEDESCRIPTION like", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionNotLike(String value) {
            addCriterion("COLORCODEDESCRIPTION not like", value, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionIn(List<String> values) {
            addCriterion("COLORCODEDESCRIPTION in", values, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionNotIn(List<String> values) {
            addCriterion("COLORCODEDESCRIPTION not in", values, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionBetween(String value1, String value2) {
            addCriterion("COLORCODEDESCRIPTION between", value1, value2, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andColorcodedescriptionNotBetween(String value1, String value2) {
            addCriterion("COLORCODEDESCRIPTION not between", value1, value2, "colorcodedescription");
            return (Criteria) this;
        }

        public Criteria andFactorytypeIsNull() {
            addCriterion("FACTORYTYPE is null");
            return (Criteria) this;
        }

        public Criteria andFactorytypeIsNotNull() {
            addCriterion("FACTORYTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFactorytypeEqualTo(String value) {
            addCriterion("FACTORYTYPE =", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeNotEqualTo(String value) {
            addCriterion("FACTORYTYPE <>", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeGreaterThan(String value) {
            addCriterion("FACTORYTYPE >", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeGreaterThanOrEqualTo(String value) {
            addCriterion("FACTORYTYPE >=", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeLessThan(String value) {
            addCriterion("FACTORYTYPE <", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeLessThanOrEqualTo(String value) {
            addCriterion("FACTORYTYPE <=", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeLike(String value) {
            addCriterion("FACTORYTYPE like", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeNotLike(String value) {
            addCriterion("FACTORYTYPE not like", value, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeIn(List<String> values) {
            addCriterion("FACTORYTYPE in", values, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeNotIn(List<String> values) {
            addCriterion("FACTORYTYPE not in", values, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeBetween(String value1, String value2) {
            addCriterion("FACTORYTYPE between", value1, value2, "factorytype");
            return (Criteria) this;
        }

        public Criteria andFactorytypeNotBetween(String value1, String value2) {
            addCriterion("FACTORYTYPE not between", value1, value2, "factorytype");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionIsNull() {
            addCriterion("TYPECODEDESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionIsNotNull() {
            addCriterion("TYPECODEDESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionEqualTo(String value) {
            addCriterion("TYPECODEDESCRIPTION =", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionNotEqualTo(String value) {
            addCriterion("TYPECODEDESCRIPTION <>", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionGreaterThan(String value) {
            addCriterion("TYPECODEDESCRIPTION >", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("TYPECODEDESCRIPTION >=", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionLessThan(String value) {
            addCriterion("TYPECODEDESCRIPTION <", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionLessThanOrEqualTo(String value) {
            addCriterion("TYPECODEDESCRIPTION <=", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionLike(String value) {
            addCriterion("TYPECODEDESCRIPTION like", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionNotLike(String value) {
            addCriterion("TYPECODEDESCRIPTION not like", value, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionIn(List<String> values) {
            addCriterion("TYPECODEDESCRIPTION in", values, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionNotIn(List<String> values) {
            addCriterion("TYPECODEDESCRIPTION not in", values, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionBetween(String value1, String value2) {
            addCriterion("TYPECODEDESCRIPTION between", value1, value2, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andTypecodedescriptionNotBetween(String value1, String value2) {
            addCriterion("TYPECODEDESCRIPTION not between", value1, value2, "typecodedescription");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidIsNull() {
            addCriterion("CURRENTLOCATIONID is null");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidIsNotNull() {
            addCriterion("CURRENTLOCATIONID is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidEqualTo(BigDecimal value) {
            addCriterion("CURRENTLOCATIONID =", value, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidNotEqualTo(BigDecimal value) {
            addCriterion("CURRENTLOCATIONID <>", value, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidGreaterThan(BigDecimal value) {
            addCriterion("CURRENTLOCATIONID >", value, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CURRENTLOCATIONID >=", value, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidLessThan(BigDecimal value) {
            addCriterion("CURRENTLOCATIONID <", value, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CURRENTLOCATIONID <=", value, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidIn(List<BigDecimal> values) {
            addCriterion("CURRENTLOCATIONID in", values, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidNotIn(List<BigDecimal> values) {
            addCriterion("CURRENTLOCATIONID not in", values, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURRENTLOCATIONID between", value1, value2, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andCurrentlocationidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURRENTLOCATIONID not between", value1, value2, "currentlocationid");
            return (Criteria) this;
        }

        public Criteria andExportcountryIsNull() {
            addCriterion("EXPORTCOUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andExportcountryIsNotNull() {
            addCriterion("EXPORTCOUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andExportcountryEqualTo(String value) {
            addCriterion("EXPORTCOUNTRY =", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryNotEqualTo(String value) {
            addCriterion("EXPORTCOUNTRY <>", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryGreaterThan(String value) {
            addCriterion("EXPORTCOUNTRY >", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryGreaterThanOrEqualTo(String value) {
            addCriterion("EXPORTCOUNTRY >=", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryLessThan(String value) {
            addCriterion("EXPORTCOUNTRY <", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryLessThanOrEqualTo(String value) {
            addCriterion("EXPORTCOUNTRY <=", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryLike(String value) {
            addCriterion("EXPORTCOUNTRY like", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryNotLike(String value) {
            addCriterion("EXPORTCOUNTRY not like", value, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryIn(List<String> values) {
            addCriterion("EXPORTCOUNTRY in", values, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryNotIn(List<String> values) {
            addCriterion("EXPORTCOUNTRY not in", values, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryBetween(String value1, String value2) {
            addCriterion("EXPORTCOUNTRY between", value1, value2, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andExportcountryNotBetween(String value1, String value2) {
            addCriterion("EXPORTCOUNTRY not between", value1, value2, "exportcountry");
            return (Criteria) this;
        }

        public Criteria andProcessroundIsNull() {
            addCriterion("PROCESSROUND is null");
            return (Criteria) this;
        }

        public Criteria andProcessroundIsNotNull() {
            addCriterion("PROCESSROUND is not null");
            return (Criteria) this;
        }

        public Criteria andProcessroundEqualTo(BigDecimal value) {
            addCriterion("PROCESSROUND =", value, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundNotEqualTo(BigDecimal value) {
            addCriterion("PROCESSROUND <>", value, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundGreaterThan(BigDecimal value) {
            addCriterion("PROCESSROUND >", value, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESSROUND >=", value, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundLessThan(BigDecimal value) {
            addCriterion("PROCESSROUND <", value, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESSROUND <=", value, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundIn(List<BigDecimal> values) {
            addCriterion("PROCESSROUND in", values, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundNotIn(List<BigDecimal> values) {
            addCriterion("PROCESSROUND not in", values, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESSROUND between", value1, value2, "processround");
            return (Criteria) this;
        }

        public Criteria andProcessroundNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESSROUND not between", value1, value2, "processround");
            return (Criteria) this;
        }

        public Criteria andReceiveddtIsNull() {
            addCriterion("RECEIVEDDT is null");
            return (Criteria) this;
        }

        public Criteria andReceiveddtIsNotNull() {
            addCriterion("RECEIVEDDT is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveddtEqualTo(String value) {
            addCriterion("RECEIVEDDT =", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtNotEqualTo(String value) {
            addCriterion("RECEIVEDDT <>", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtGreaterThan(String value) {
            addCriterion("RECEIVEDDT >", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtGreaterThanOrEqualTo(String value) {
            addCriterion("RECEIVEDDT >=", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtLessThan(String value) {
            addCriterion("RECEIVEDDT <", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtLessThanOrEqualTo(String value) {
            addCriterion("RECEIVEDDT <=", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtLike(String value) {
            addCriterion("RECEIVEDDT like", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtNotLike(String value) {
            addCriterion("RECEIVEDDT not like", value, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtIn(List<String> values) {
            addCriterion("RECEIVEDDT in", values, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtNotIn(List<String> values) {
            addCriterion("RECEIVEDDT not in", values, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtBetween(String value1, String value2) {
            addCriterion("RECEIVEDDT between", value1, value2, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddtNotBetween(String value1, String value2) {
            addCriterion("RECEIVEDDT not between", value1, value2, "receiveddt");
            return (Criteria) this;
        }

        public Criteria andReceiveddateIsNull() {
            addCriterion("RECEIVEDDATE is null");
            return (Criteria) this;
        }

        public Criteria andReceiveddateIsNotNull() {
            addCriterion("RECEIVEDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveddateEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDDATE =", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateNotEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDDATE <>", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateGreaterThan(BigDecimal value) {
            addCriterion("RECEIVEDDATE >", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDDATE >=", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateLessThan(BigDecimal value) {
            addCriterion("RECEIVEDDATE <", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDDATE <=", value, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateIn(List<BigDecimal> values) {
            addCriterion("RECEIVEDDATE in", values, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateNotIn(List<BigDecimal> values) {
            addCriterion("RECEIVEDDATE not in", values, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECEIVEDDATE between", value1, value2, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andReceiveddateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECEIVEDDATE not between", value1, value2, "receiveddate");
            return (Criteria) this;
        }

        public Criteria andModelIsNull() {
            addCriterion("MODEL is null");
            return (Criteria) this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("MODEL is not null");
            return (Criteria) this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("MODEL =", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("MODEL <>", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("MODEL >", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("MODEL >=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("MODEL <", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("MODEL <=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("MODEL like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("MODEL not like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("MODEL in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("MODEL not in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("MODEL between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("MODEL not between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andRfidtagIsNull() {
            addCriterion("RFIDTAG is null");
            return (Criteria) this;
        }

        public Criteria andRfidtagIsNotNull() {
            addCriterion("RFIDTAG is not null");
            return (Criteria) this;
        }

        public Criteria andRfidtagEqualTo(String value) {
            addCriterion("RFIDTAG =", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagNotEqualTo(String value) {
            addCriterion("RFIDTAG <>", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagGreaterThan(String value) {
            addCriterion("RFIDTAG >", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagGreaterThanOrEqualTo(String value) {
            addCriterion("RFIDTAG >=", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagLessThan(String value) {
            addCriterion("RFIDTAG <", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagLessThanOrEqualTo(String value) {
            addCriterion("RFIDTAG <=", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagLike(String value) {
            addCriterion("RFIDTAG like", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagNotLike(String value) {
            addCriterion("RFIDTAG not like", value, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagIn(List<String> values) {
            addCriterion("RFIDTAG in", values, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagNotIn(List<String> values) {
            addCriterion("RFIDTAG not in", values, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagBetween(String value1, String value2) {
            addCriterion("RFIDTAG between", value1, value2, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andRfidtagNotBetween(String value1, String value2) {
            addCriterion("RFIDTAG not between", value1, value2, "rfidtag");
            return (Criteria) this;
        }

        public Criteria andCheckeroidIsNull() {
            addCriterion("CHECKEROID is null");
            return (Criteria) this;
        }

        public Criteria andCheckeroidIsNotNull() {
            addCriterion("CHECKEROID is not null");
            return (Criteria) this;
        }

        public Criteria andCheckeroidEqualTo(String value) {
            addCriterion("CHECKEROID =", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidNotEqualTo(String value) {
            addCriterion("CHECKEROID <>", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidGreaterThan(String value) {
            addCriterion("CHECKEROID >", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKEROID >=", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidLessThan(String value) {
            addCriterion("CHECKEROID <", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidLessThanOrEqualTo(String value) {
            addCriterion("CHECKEROID <=", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidLike(String value) {
            addCriterion("CHECKEROID like", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidNotLike(String value) {
            addCriterion("CHECKEROID not like", value, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidIn(List<String> values) {
            addCriterion("CHECKEROID in", values, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidNotIn(List<String> values) {
            addCriterion("CHECKEROID not in", values, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidBetween(String value1, String value2) {
            addCriterion("CHECKEROID between", value1, value2, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andCheckeroidNotBetween(String value1, String value2) {
            addCriterion("CHECKEROID not between", value1, value2, "checkeroid");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeIsNull() {
            addCriterion("ISVQJUDGE is null");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeIsNotNull() {
            addCriterion("ISVQJUDGE is not null");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeEqualTo(String value) {
            addCriterion("ISVQJUDGE =", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeNotEqualTo(String value) {
            addCriterion("ISVQJUDGE <>", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeGreaterThan(String value) {
            addCriterion("ISVQJUDGE >", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeGreaterThanOrEqualTo(String value) {
            addCriterion("ISVQJUDGE >=", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeLessThan(String value) {
            addCriterion("ISVQJUDGE <", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeLessThanOrEqualTo(String value) {
            addCriterion("ISVQJUDGE <=", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeLike(String value) {
            addCriterion("ISVQJUDGE like", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeNotLike(String value) {
            addCriterion("ISVQJUDGE not like", value, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeIn(List<String> values) {
            addCriterion("ISVQJUDGE in", values, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeNotIn(List<String> values) {
            addCriterion("ISVQJUDGE not in", values, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeBetween(String value1, String value2) {
            addCriterion("ISVQJUDGE between", value1, value2, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andIsvqjudgeNotBetween(String value1, String value2) {
            addCriterion("ISVQJUDGE not between", value1, value2, "isvqjudge");
            return (Criteria) this;
        }

        public Criteria andTstypeIsNull() {
            addCriterion("TSTYPE is null");
            return (Criteria) this;
        }

        public Criteria andTstypeIsNotNull() {
            addCriterion("TSTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTstypeEqualTo(String value) {
            addCriterion("TSTYPE =", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeNotEqualTo(String value) {
            addCriterion("TSTYPE <>", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeGreaterThan(String value) {
            addCriterion("TSTYPE >", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeGreaterThanOrEqualTo(String value) {
            addCriterion("TSTYPE >=", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeLessThan(String value) {
            addCriterion("TSTYPE <", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeLessThanOrEqualTo(String value) {
            addCriterion("TSTYPE <=", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeLike(String value) {
            addCriterion("TSTYPE like", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeNotLike(String value) {
            addCriterion("TSTYPE not like", value, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeIn(List<String> values) {
            addCriterion("TSTYPE in", values, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeNotIn(List<String> values) {
            addCriterion("TSTYPE not in", values, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeBetween(String value1, String value2) {
            addCriterion("TSTYPE between", value1, value2, "tstype");
            return (Criteria) this;
        }

        public Criteria andTstypeNotBetween(String value1, String value2) {
            addCriterion("TSTYPE not between", value1, value2, "tstype");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("CREATEBY is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("CREATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("CREATEBY =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("CREATEBY <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("CREATEBY >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEBY >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("CREATEBY <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("CREATEBY <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("CREATEBY like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("CREATEBY not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("CREATEBY in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("CREATEBY not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("CREATEBY between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("CREATEBY not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNull() {
            addCriterion("CREATEDT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNotNull() {
            addCriterion("CREATEDT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtEqualTo(String value) {
            addCriterion("CREATEDT =", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotEqualTo(String value) {
            addCriterion("CREATEDT <>", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThan(String value) {
            addCriterion("CREATEDT >", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEDT >=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThan(String value) {
            addCriterion("CREATEDT <", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThanOrEqualTo(String value) {
            addCriterion("CREATEDT <=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLike(String value) {
            addCriterion("CREATEDT like", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotLike(String value) {
            addCriterion("CREATEDT not like", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtIn(List<String> values) {
            addCriterion("CREATEDT in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotIn(List<String> values) {
            addCriterion("CREATEDT not in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtBetween(String value1, String value2) {
            addCriterion("CREATEDT between", value1, value2, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotBetween(String value1, String value2) {
            addCriterion("CREATEDT not between", value1, value2, "createdt");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNull() {
            addCriterion("MODIFYBY is null");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNotNull() {
            addCriterion("MODIFYBY is not null");
            return (Criteria) this;
        }

        public Criteria andModifybyEqualTo(String value) {
            addCriterion("MODIFYBY =", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotEqualTo(String value) {
            addCriterion("MODIFYBY <>", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThan(String value) {
            addCriterion("MODIFYBY >", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYBY >=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThan(String value) {
            addCriterion("MODIFYBY <", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThanOrEqualTo(String value) {
            addCriterion("MODIFYBY <=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLike(String value) {
            addCriterion("MODIFYBY like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotLike(String value) {
            addCriterion("MODIFYBY not like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyIn(List<String> values) {
            addCriterion("MODIFYBY in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotIn(List<String> values) {
            addCriterion("MODIFYBY not in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyBetween(String value1, String value2) {
            addCriterion("MODIFYBY between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotBetween(String value1, String value2) {
            addCriterion("MODIFYBY not between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifydtIsNull() {
            addCriterion("MODIFYDT is null");
            return (Criteria) this;
        }

        public Criteria andModifydtIsNotNull() {
            addCriterion("MODIFYDT is not null");
            return (Criteria) this;
        }

        public Criteria andModifydtEqualTo(String value) {
            addCriterion("MODIFYDT =", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtNotEqualTo(String value) {
            addCriterion("MODIFYDT <>", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtGreaterThan(String value) {
            addCriterion("MODIFYDT >", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYDT >=", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtLessThan(String value) {
            addCriterion("MODIFYDT <", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtLessThanOrEqualTo(String value) {
            addCriterion("MODIFYDT <=", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtLike(String value) {
            addCriterion("MODIFYDT like", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtNotLike(String value) {
            addCriterion("MODIFYDT not like", value, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtIn(List<String> values) {
            addCriterion("MODIFYDT in", values, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtNotIn(List<String> values) {
            addCriterion("MODIFYDT not in", values, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtBetween(String value1, String value2) {
            addCriterion("MODIFYDT between", value1, value2, "modifydt");
            return (Criteria) this;
        }

        public Criteria andModifydtNotBetween(String value1, String value2) {
            addCriterion("MODIFYDT not between", value1, value2, "modifydt");
            return (Criteria) this;
        }

        public Criteria andCarstatusIsNull() {
            addCriterion("CARSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andCarstatusIsNotNull() {
            addCriterion("CARSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andCarstatusEqualTo(String value) {
            addCriterion("CARSTATUS =", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotEqualTo(String value) {
            addCriterion("CARSTATUS <>", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusGreaterThan(String value) {
            addCriterion("CARSTATUS >", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusGreaterThanOrEqualTo(String value) {
            addCriterion("CARSTATUS >=", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusLessThan(String value) {
            addCriterion("CARSTATUS <", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusLessThanOrEqualTo(String value) {
            addCriterion("CARSTATUS <=", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusLike(String value) {
            addCriterion("CARSTATUS like", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotLike(String value) {
            addCriterion("CARSTATUS not like", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusIn(List<String> values) {
            addCriterion("CARSTATUS in", values, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotIn(List<String> values) {
            addCriterion("CARSTATUS not in", values, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusBetween(String value1, String value2) {
            addCriterion("CARSTATUS between", value1, value2, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotBetween(String value1, String value2) {
            addCriterion("CARSTATUS not between", value1, value2, "carstatus");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeIsNull() {
            addCriterion("RECEIVEDTIME is null");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeIsNotNull() {
            addCriterion("RECEIVEDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDTIME =", value, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeNotEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDTIME <>", value, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeGreaterThan(BigDecimal value) {
            addCriterion("RECEIVEDTIME >", value, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDTIME >=", value, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeLessThan(BigDecimal value) {
            addCriterion("RECEIVEDTIME <", value, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RECEIVEDTIME <=", value, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeIn(List<BigDecimal> values) {
            addCriterion("RECEIVEDTIME in", values, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeNotIn(List<BigDecimal> values) {
            addCriterion("RECEIVEDTIME not in", values, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECEIVEDTIME between", value1, value2, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andReceivedtimeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECEIVEDTIME not between", value1, value2, "receivedtime");
            return (Criteria) this;
        }

        public Criteria andFactorymodelIsNull() {
            addCriterion("FACTORYMODEL is null");
            return (Criteria) this;
        }

        public Criteria andFactorymodelIsNotNull() {
            addCriterion("FACTORYMODEL is not null");
            return (Criteria) this;
        }

        public Criteria andFactorymodelEqualTo(String value) {
            addCriterion("FACTORYMODEL =", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelNotEqualTo(String value) {
            addCriterion("FACTORYMODEL <>", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelGreaterThan(String value) {
            addCriterion("FACTORYMODEL >", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelGreaterThanOrEqualTo(String value) {
            addCriterion("FACTORYMODEL >=", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelLessThan(String value) {
            addCriterion("FACTORYMODEL <", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelLessThanOrEqualTo(String value) {
            addCriterion("FACTORYMODEL <=", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelLike(String value) {
            addCriterion("FACTORYMODEL like", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelNotLike(String value) {
            addCriterion("FACTORYMODEL not like", value, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelIn(List<String> values) {
            addCriterion("FACTORYMODEL in", values, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelNotIn(List<String> values) {
            addCriterion("FACTORYMODEL not in", values, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelBetween(String value1, String value2) {
            addCriterion("FACTORYMODEL between", value1, value2, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andFactorymodelNotBetween(String value1, String value2) {
            addCriterion("FACTORYMODEL not between", value1, value2, "factorymodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelIsNull() {
            addCriterion("SALEMODEL is null");
            return (Criteria) this;
        }

        public Criteria andSalemodelIsNotNull() {
            addCriterion("SALEMODEL is not null");
            return (Criteria) this;
        }

        public Criteria andSalemodelEqualTo(String value) {
            addCriterion("SALEMODEL =", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelNotEqualTo(String value) {
            addCriterion("SALEMODEL <>", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelGreaterThan(String value) {
            addCriterion("SALEMODEL >", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelGreaterThanOrEqualTo(String value) {
            addCriterion("SALEMODEL >=", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelLessThan(String value) {
            addCriterion("SALEMODEL <", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelLessThanOrEqualTo(String value) {
            addCriterion("SALEMODEL <=", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelLike(String value) {
            addCriterion("SALEMODEL like", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelNotLike(String value) {
            addCriterion("SALEMODEL not like", value, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelIn(List<String> values) {
            addCriterion("SALEMODEL in", values, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelNotIn(List<String> values) {
            addCriterion("SALEMODEL not in", values, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelBetween(String value1, String value2) {
            addCriterion("SALEMODEL between", value1, value2, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalemodelNotBetween(String value1, String value2) {
            addCriterion("SALEMODEL not between", value1, value2, "salemodel");
            return (Criteria) this;
        }

        public Criteria andSalecolorIsNull() {
            addCriterion("SALECOLOR is null");
            return (Criteria) this;
        }

        public Criteria andSalecolorIsNotNull() {
            addCriterion("SALECOLOR is not null");
            return (Criteria) this;
        }

        public Criteria andSalecolorEqualTo(String value) {
            addCriterion("SALECOLOR =", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorNotEqualTo(String value) {
            addCriterion("SALECOLOR <>", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorGreaterThan(String value) {
            addCriterion("SALECOLOR >", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorGreaterThanOrEqualTo(String value) {
            addCriterion("SALECOLOR >=", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorLessThan(String value) {
            addCriterion("SALECOLOR <", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorLessThanOrEqualTo(String value) {
            addCriterion("SALECOLOR <=", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorLike(String value) {
            addCriterion("SALECOLOR like", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorNotLike(String value) {
            addCriterion("SALECOLOR not like", value, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorIn(List<String> values) {
            addCriterion("SALECOLOR in", values, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorNotIn(List<String> values) {
            addCriterion("SALECOLOR not in", values, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorBetween(String value1, String value2) {
            addCriterion("SALECOLOR between", value1, value2, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSalecolorNotBetween(String value1, String value2) {
            addCriterion("SALECOLOR not between", value1, value2, "salecolor");
            return (Criteria) this;
        }

        public Criteria andSaletypeIsNull() {
            addCriterion("SALETYPE is null");
            return (Criteria) this;
        }

        public Criteria andSaletypeIsNotNull() {
            addCriterion("SALETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSaletypeEqualTo(String value) {
            addCriterion("SALETYPE =", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeNotEqualTo(String value) {
            addCriterion("SALETYPE <>", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeGreaterThan(String value) {
            addCriterion("SALETYPE >", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeGreaterThanOrEqualTo(String value) {
            addCriterion("SALETYPE >=", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeLessThan(String value) {
            addCriterion("SALETYPE <", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeLessThanOrEqualTo(String value) {
            addCriterion("SALETYPE <=", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeLike(String value) {
            addCriterion("SALETYPE like", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeNotLike(String value) {
            addCriterion("SALETYPE not like", value, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeIn(List<String> values) {
            addCriterion("SALETYPE in", values, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeNotIn(List<String> values) {
            addCriterion("SALETYPE not in", values, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeBetween(String value1, String value2) {
            addCriterion("SALETYPE between", value1, value2, "saletype");
            return (Criteria) this;
        }

        public Criteria andSaletypeNotBetween(String value1, String value2) {
            addCriterion("SALETYPE not between", value1, value2, "saletype");
            return (Criteria) this;
        }

        public Criteria andMtocIsNull() {
            addCriterion("MTOC is null");
            return (Criteria) this;
        }

        public Criteria andMtocIsNotNull() {
            addCriterion("MTOC is not null");
            return (Criteria) this;
        }

        public Criteria andMtocEqualTo(String value) {
            addCriterion("MTOC =", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocNotEqualTo(String value) {
            addCriterion("MTOC <>", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocGreaterThan(String value) {
            addCriterion("MTOC >", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocGreaterThanOrEqualTo(String value) {
            addCriterion("MTOC >=", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocLessThan(String value) {
            addCriterion("MTOC <", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocLessThanOrEqualTo(String value) {
            addCriterion("MTOC <=", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocLike(String value) {
            addCriterion("MTOC like", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocNotLike(String value) {
            addCriterion("MTOC not like", value, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocIn(List<String> values) {
            addCriterion("MTOC in", values, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocNotIn(List<String> values) {
            addCriterion("MTOC not in", values, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocBetween(String value1, String value2) {
            addCriterion("MTOC between", value1, value2, "mtoc");
            return (Criteria) this;
        }

        public Criteria andMtocNotBetween(String value1, String value2) {
            addCriterion("MTOC not between", value1, value2, "mtoc");
            return (Criteria) this;
        }

        public Criteria andExcisetaxIsNull() {
            addCriterion("EXCISETAX is null");
            return (Criteria) this;
        }

        public Criteria andExcisetaxIsNotNull() {
            addCriterion("EXCISETAX is not null");
            return (Criteria) this;
        }

        public Criteria andExcisetaxEqualTo(String value) {
            addCriterion("EXCISETAX =", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxNotEqualTo(String value) {
            addCriterion("EXCISETAX <>", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxGreaterThan(String value) {
            addCriterion("EXCISETAX >", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxGreaterThanOrEqualTo(String value) {
            addCriterion("EXCISETAX >=", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxLessThan(String value) {
            addCriterion("EXCISETAX <", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxLessThanOrEqualTo(String value) {
            addCriterion("EXCISETAX <=", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxLike(String value) {
            addCriterion("EXCISETAX like", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxNotLike(String value) {
            addCriterion("EXCISETAX not like", value, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxIn(List<String> values) {
            addCriterion("EXCISETAX in", values, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxNotIn(List<String> values) {
            addCriterion("EXCISETAX not in", values, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxBetween(String value1, String value2) {
            addCriterion("EXCISETAX between", value1, value2, "excisetax");
            return (Criteria) this;
        }

        public Criteria andExcisetaxNotBetween(String value1, String value2) {
            addCriterion("EXCISETAX not between", value1, value2, "excisetax");
            return (Criteria) this;
        }

        public Criteria andAfoffdateIsNull() {
            addCriterion("AFOFFDATE is null");
            return (Criteria) this;
        }

        public Criteria andAfoffdateIsNotNull() {
            addCriterion("AFOFFDATE is not null");
            return (Criteria) this;
        }

        public Criteria andAfoffdateEqualTo(Short value) {
            addCriterion("AFOFFDATE =", value, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateNotEqualTo(Short value) {
            addCriterion("AFOFFDATE <>", value, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateGreaterThan(Short value) {
            addCriterion("AFOFFDATE >", value, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateGreaterThanOrEqualTo(Short value) {
            addCriterion("AFOFFDATE >=", value, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateLessThan(Short value) {
            addCriterion("AFOFFDATE <", value, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateLessThanOrEqualTo(Short value) {
            addCriterion("AFOFFDATE <=", value, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateIn(List<Short> values) {
            addCriterion("AFOFFDATE in", values, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateNotIn(List<Short> values) {
            addCriterion("AFOFFDATE not in", values, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateBetween(Short value1, Short value2) {
            addCriterion("AFOFFDATE between", value1, value2, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfoffdateNotBetween(Short value1, Short value2) {
            addCriterion("AFOFFDATE not between", value1, value2, "afoffdate");
            return (Criteria) this;
        }

        public Criteria andAfofftimeIsNull() {
            addCriterion("AFOFFTIME is null");
            return (Criteria) this;
        }

        public Criteria andAfofftimeIsNotNull() {
            addCriterion("AFOFFTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAfofftimeEqualTo(Short value) {
            addCriterion("AFOFFTIME =", value, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeNotEqualTo(Short value) {
            addCriterion("AFOFFTIME <>", value, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeGreaterThan(Short value) {
            addCriterion("AFOFFTIME >", value, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeGreaterThanOrEqualTo(Short value) {
            addCriterion("AFOFFTIME >=", value, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeLessThan(Short value) {
            addCriterion("AFOFFTIME <", value, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeLessThanOrEqualTo(Short value) {
            addCriterion("AFOFFTIME <=", value, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeIn(List<Short> values) {
            addCriterion("AFOFFTIME in", values, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeNotIn(List<Short> values) {
            addCriterion("AFOFFTIME not in", values, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeBetween(Short value1, Short value2) {
            addCriterion("AFOFFTIME between", value1, value2, "afofftime");
            return (Criteria) this;
        }

        public Criteria andAfofftimeNotBetween(Short value1, Short value2) {
            addCriterion("AFOFFTIME not between", value1, value2, "afofftime");
            return (Criteria) this;
        }

        public Criteria andFactorynoIsNull() {
            addCriterion("FACTORYNO is null");
            return (Criteria) this;
        }

        public Criteria andFactorynoIsNotNull() {
            addCriterion("FACTORYNO is not null");
            return (Criteria) this;
        }

        public Criteria andFactorynoEqualTo(Short value) {
            addCriterion("FACTORYNO =", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoNotEqualTo(Short value) {
            addCriterion("FACTORYNO <>", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoGreaterThan(Short value) {
            addCriterion("FACTORYNO >", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoGreaterThanOrEqualTo(Short value) {
            addCriterion("FACTORYNO >=", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoLessThan(Short value) {
            addCriterion("FACTORYNO <", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoLessThanOrEqualTo(Short value) {
            addCriterion("FACTORYNO <=", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoIn(List<Short> values) {
            addCriterion("FACTORYNO in", values, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoNotIn(List<Short> values) {
            addCriterion("FACTORYNO not in", values, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoBetween(Short value1, Short value2) {
            addCriterion("FACTORYNO between", value1, value2, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoNotBetween(Short value1, Short value2) {
            addCriterion("FACTORYNO not between", value1, value2, "factoryno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoIsNull() {
            addCriterion("KDLOTNO is null");
            return (Criteria) this;
        }

        public Criteria andKdlotnoIsNotNull() {
            addCriterion("KDLOTNO is not null");
            return (Criteria) this;
        }

        public Criteria andKdlotnoEqualTo(String value) {
            addCriterion("KDLOTNO =", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoNotEqualTo(String value) {
            addCriterion("KDLOTNO <>", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoGreaterThan(String value) {
            addCriterion("KDLOTNO >", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoGreaterThanOrEqualTo(String value) {
            addCriterion("KDLOTNO >=", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoLessThan(String value) {
            addCriterion("KDLOTNO <", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoLessThanOrEqualTo(String value) {
            addCriterion("KDLOTNO <=", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoLike(String value) {
            addCriterion("KDLOTNO like", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoNotLike(String value) {
            addCriterion("KDLOTNO not like", value, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoIn(List<String> values) {
            addCriterion("KDLOTNO in", values, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoNotIn(List<String> values) {
            addCriterion("KDLOTNO not in", values, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoBetween(String value1, String value2) {
            addCriterion("KDLOTNO between", value1, value2, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andKdlotnoNotBetween(String value1, String value2) {
            addCriterion("KDLOTNO not between", value1, value2, "kdlotno");
            return (Criteria) this;
        }

        public Criteria andPlancodeIsNull() {
            addCriterion("PLANCODE is null");
            return (Criteria) this;
        }

        public Criteria andPlancodeIsNotNull() {
            addCriterion("PLANCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPlancodeEqualTo(String value) {
            addCriterion("PLANCODE =", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeNotEqualTo(String value) {
            addCriterion("PLANCODE <>", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeGreaterThan(String value) {
            addCriterion("PLANCODE >", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeGreaterThanOrEqualTo(String value) {
            addCriterion("PLANCODE >=", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeLessThan(String value) {
            addCriterion("PLANCODE <", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeLessThanOrEqualTo(String value) {
            addCriterion("PLANCODE <=", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeLike(String value) {
            addCriterion("PLANCODE like", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeNotLike(String value) {
            addCriterion("PLANCODE not like", value, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeIn(List<String> values) {
            addCriterion("PLANCODE in", values, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeNotIn(List<String> values) {
            addCriterion("PLANCODE not in", values, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeBetween(String value1, String value2) {
            addCriterion("PLANCODE between", value1, value2, "plancode");
            return (Criteria) this;
        }

        public Criteria andPlancodeNotBetween(String value1, String value2) {
            addCriterion("PLANCODE not between", value1, value2, "plancode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 11 16:09:56 ICT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HONDA.T_NDCRECEIVED
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}