package com.model;

import java.math.BigDecimal;

public class TNdcreceived {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.OID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.FRAMENO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String frameno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.ENGINENO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String engineno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.INSPECTIONRESULT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String inspectionresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.ISEXPORT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String isexport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.FACTORYCOLOR
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String factorycolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.COLORCODEDESCRIPTION
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String colorcodedescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.FACTORYTYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String factorytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.TYPECODEDESCRIPTION
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String typecodedescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.CURRENTLOCATIONID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private BigDecimal currentlocationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.EXPORTCOUNTRY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String exportcountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.PROCESSROUND
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private BigDecimal processround;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.RECEIVEDDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String receiveddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.RECEIVEDDATE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private BigDecimal receiveddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.MODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.RFIDTAG
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String rfidtag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.CHECKEROID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String checkeroid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.ISVQJUDGE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String isvqjudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.TSTYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String tstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.STATUS
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.CREATEBY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.CREATEDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String createdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.MODIFYBY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String modifyby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.MODIFYDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String modifydt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.CARSTATUS
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String carstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.RECEIVEDTIME
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private BigDecimal receivedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.FACTORYMODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String factorymodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.SALEMODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String salemodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.SALECOLOR
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String salecolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.SALETYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String saletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.MTOC
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String mtoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.EXCISETAX
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String excisetax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.AFOFFDATE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private BigDecimal afoffdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.AFOFFTIME
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private BigDecimal afofftime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.FACTORYNO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private Short factoryno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.KDLOTNO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String kdlotno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONDA.T_NDCRECEIVED.PLANCODE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    private String plancode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.OID
     *
     * @return the value of HONDA.T_NDCRECEIVED.OID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.OID
     *
     * @param oid the value for HONDA.T_NDCRECEIVED.OID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.FRAMENO
     *
     * @return the value of HONDA.T_NDCRECEIVED.FRAMENO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getFrameno() {
        return frameno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.FRAMENO
     *
     * @param frameno the value for HONDA.T_NDCRECEIVED.FRAMENO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setFrameno(String frameno) {
        this.frameno = frameno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.ENGINENO
     *
     * @return the value of HONDA.T_NDCRECEIVED.ENGINENO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getEngineno() {
        return engineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.ENGINENO
     *
     * @param engineno the value for HONDA.T_NDCRECEIVED.ENGINENO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setEngineno(String engineno) {
        this.engineno = engineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.INSPECTIONRESULT
     *
     * @return the value of HONDA.T_NDCRECEIVED.INSPECTIONRESULT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getInspectionresult() {
        return inspectionresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.INSPECTIONRESULT
     *
     * @param inspectionresult the value for HONDA.T_NDCRECEIVED.INSPECTIONRESULT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setInspectionresult(String inspectionresult) {
        this.inspectionresult = inspectionresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.ISEXPORT
     *
     * @return the value of HONDA.T_NDCRECEIVED.ISEXPORT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getIsexport() {
        return isexport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.ISEXPORT
     *
     * @param isexport the value for HONDA.T_NDCRECEIVED.ISEXPORT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setIsexport(String isexport) {
        this.isexport = isexport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.FACTORYCOLOR
     *
     * @return the value of HONDA.T_NDCRECEIVED.FACTORYCOLOR
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getFactorycolor() {
        return factorycolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.FACTORYCOLOR
     *
     * @param factorycolor the value for HONDA.T_NDCRECEIVED.FACTORYCOLOR
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setFactorycolor(String factorycolor) {
        this.factorycolor = factorycolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.COLORCODEDESCRIPTION
     *
     * @return the value of HONDA.T_NDCRECEIVED.COLORCODEDESCRIPTION
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getColorcodedescription() {
        return colorcodedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.COLORCODEDESCRIPTION
     *
     * @param colorcodedescription the value for HONDA.T_NDCRECEIVED.COLORCODEDESCRIPTION
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setColorcodedescription(String colorcodedescription) {
        this.colorcodedescription = colorcodedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.FACTORYTYPE
     *
     * @return the value of HONDA.T_NDCRECEIVED.FACTORYTYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getFactorytype() {
        return factorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.FACTORYTYPE
     *
     * @param factorytype the value for HONDA.T_NDCRECEIVED.FACTORYTYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setFactorytype(String factorytype) {
        this.factorytype = factorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.TYPECODEDESCRIPTION
     *
     * @return the value of HONDA.T_NDCRECEIVED.TYPECODEDESCRIPTION
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getTypecodedescription() {
        return typecodedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.TYPECODEDESCRIPTION
     *
     * @param typecodedescription the value for HONDA.T_NDCRECEIVED.TYPECODEDESCRIPTION
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setTypecodedescription(String typecodedescription) {
        this.typecodedescription = typecodedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.CURRENTLOCATIONID
     *
     * @return the value of HONDA.T_NDCRECEIVED.CURRENTLOCATIONID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public BigDecimal getCurrentlocationid() {
        return currentlocationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.CURRENTLOCATIONID
     *
     * @param currentlocationid the value for HONDA.T_NDCRECEIVED.CURRENTLOCATIONID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setCurrentlocationid(BigDecimal currentlocationid) {
        this.currentlocationid = currentlocationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.EXPORTCOUNTRY
     *
     * @return the value of HONDA.T_NDCRECEIVED.EXPORTCOUNTRY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getExportcountry() {
        return exportcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.EXPORTCOUNTRY
     *
     * @param exportcountry the value for HONDA.T_NDCRECEIVED.EXPORTCOUNTRY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setExportcountry(String exportcountry) {
        this.exportcountry = exportcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.PROCESSROUND
     *
     * @return the value of HONDA.T_NDCRECEIVED.PROCESSROUND
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public BigDecimal getProcessround() {
        return processround;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.PROCESSROUND
     *
     * @param processround the value for HONDA.T_NDCRECEIVED.PROCESSROUND
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setProcessround(BigDecimal processround) {
        this.processround = processround;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.RECEIVEDDT
     *
     * @return the value of HONDA.T_NDCRECEIVED.RECEIVEDDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getReceiveddt() {
        return receiveddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.RECEIVEDDT
     *
     * @param receiveddt the value for HONDA.T_NDCRECEIVED.RECEIVEDDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setReceiveddt(String receiveddt) {
        this.receiveddt = receiveddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.RECEIVEDDATE
     *
     * @return the value of HONDA.T_NDCRECEIVED.RECEIVEDDATE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public BigDecimal getReceiveddate() {
        return receiveddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.RECEIVEDDATE
     *
     * @param receiveddate the value for HONDA.T_NDCRECEIVED.RECEIVEDDATE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setReceiveddate(BigDecimal receiveddate) {
        this.receiveddate = receiveddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.MODEL
     *
     * @return the value of HONDA.T_NDCRECEIVED.MODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.MODEL
     *
     * @param model the value for HONDA.T_NDCRECEIVED.MODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.RFIDTAG
     *
     * @return the value of HONDA.T_NDCRECEIVED.RFIDTAG
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getRfidtag() {
        return rfidtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.RFIDTAG
     *
     * @param rfidtag the value for HONDA.T_NDCRECEIVED.RFIDTAG
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setRfidtag(String rfidtag) {
        this.rfidtag = rfidtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.CHECKEROID
     *
     * @return the value of HONDA.T_NDCRECEIVED.CHECKEROID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getCheckeroid() {
        return checkeroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.CHECKEROID
     *
     * @param checkeroid the value for HONDA.T_NDCRECEIVED.CHECKEROID
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setCheckeroid(String checkeroid) {
        this.checkeroid = checkeroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.ISVQJUDGE
     *
     * @return the value of HONDA.T_NDCRECEIVED.ISVQJUDGE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getIsvqjudge() {
        return isvqjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.ISVQJUDGE
     *
     * @param isvqjudge the value for HONDA.T_NDCRECEIVED.ISVQJUDGE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setIsvqjudge(String isvqjudge) {
        this.isvqjudge = isvqjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.TSTYPE
     *
     * @return the value of HONDA.T_NDCRECEIVED.TSTYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getTstype() {
        return tstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.TSTYPE
     *
     * @param tstype the value for HONDA.T_NDCRECEIVED.TSTYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setTstype(String tstype) {
        this.tstype = tstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.STATUS
     *
     * @return the value of HONDA.T_NDCRECEIVED.STATUS
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.STATUS
     *
     * @param status the value for HONDA.T_NDCRECEIVED.STATUS
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.CREATEBY
     *
     * @return the value of HONDA.T_NDCRECEIVED.CREATEBY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.CREATEBY
     *
     * @param createby the value for HONDA.T_NDCRECEIVED.CREATEBY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.CREATEDT
     *
     * @return the value of HONDA.T_NDCRECEIVED.CREATEDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.CREATEDT
     *
     * @param createdt the value for HONDA.T_NDCRECEIVED.CREATEDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setCreatedt(String createdt) {
        this.createdt = createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.MODIFYBY
     *
     * @return the value of HONDA.T_NDCRECEIVED.MODIFYBY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.MODIFYBY
     *
     * @param modifyby the value for HONDA.T_NDCRECEIVED.MODIFYBY
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setModifyby(String modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.MODIFYDT
     *
     * @return the value of HONDA.T_NDCRECEIVED.MODIFYDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getModifydt() {
        return modifydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.MODIFYDT
     *
     * @param modifydt the value for HONDA.T_NDCRECEIVED.MODIFYDT
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setModifydt(String modifydt) {
        this.modifydt = modifydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.CARSTATUS
     *
     * @return the value of HONDA.T_NDCRECEIVED.CARSTATUS
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getCarstatus() {
        return carstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.CARSTATUS
     *
     * @param carstatus the value for HONDA.T_NDCRECEIVED.CARSTATUS
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setCarstatus(String carstatus) {
        this.carstatus = carstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.RECEIVEDTIME
     *
     * @return the value of HONDA.T_NDCRECEIVED.RECEIVEDTIME
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public BigDecimal getReceivedtime() {
        return receivedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.RECEIVEDTIME
     *
     * @param receivedtime the value for HONDA.T_NDCRECEIVED.RECEIVEDTIME
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setReceivedtime(BigDecimal receivedtime) {
        this.receivedtime = receivedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.FACTORYMODEL
     *
     * @return the value of HONDA.T_NDCRECEIVED.FACTORYMODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getFactorymodel() {
        return factorymodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.FACTORYMODEL
     *
     * @param factorymodel the value for HONDA.T_NDCRECEIVED.FACTORYMODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setFactorymodel(String factorymodel) {
        this.factorymodel = factorymodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.SALEMODEL
     *
     * @return the value of HONDA.T_NDCRECEIVED.SALEMODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getSalemodel() {
        return salemodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.SALEMODEL
     *
     * @param salemodel the value for HONDA.T_NDCRECEIVED.SALEMODEL
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setSalemodel(String salemodel) {
        this.salemodel = salemodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.SALECOLOR
     *
     * @return the value of HONDA.T_NDCRECEIVED.SALECOLOR
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getSalecolor() {
        return salecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.SALECOLOR
     *
     * @param salecolor the value for HONDA.T_NDCRECEIVED.SALECOLOR
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setSalecolor(String salecolor) {
        this.salecolor = salecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.SALETYPE
     *
     * @return the value of HONDA.T_NDCRECEIVED.SALETYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getSaletype() {
        return saletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.SALETYPE
     *
     * @param saletype the value for HONDA.T_NDCRECEIVED.SALETYPE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setSaletype(String saletype) {
        this.saletype = saletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.MTOC
     *
     * @return the value of HONDA.T_NDCRECEIVED.MTOC
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getMtoc() {
        return mtoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.MTOC
     *
     * @param mtoc the value for HONDA.T_NDCRECEIVED.MTOC
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setMtoc(String mtoc) {
        this.mtoc = mtoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.EXCISETAX
     *
     * @return the value of HONDA.T_NDCRECEIVED.EXCISETAX
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getExcisetax() {
        return excisetax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.EXCISETAX
     *
     * @param excisetax the value for HONDA.T_NDCRECEIVED.EXCISETAX
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setExcisetax(String excisetax) {
        this.excisetax = excisetax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.AFOFFDATE
     *
     * @return the value of HONDA.T_NDCRECEIVED.AFOFFDATE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public BigDecimal getAfoffdate() {
        return afoffdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.AFOFFDATE
     *
     * @param afoffdate the value for HONDA.T_NDCRECEIVED.AFOFFDATE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setAfoffdate(BigDecimal afoffdate) {
        this.afoffdate = afoffdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.AFOFFTIME
     *
     * @return the value of HONDA.T_NDCRECEIVED.AFOFFTIME
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public BigDecimal getAfofftime() {
        return afofftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.AFOFFTIME
     *
     * @param afofftime the value for HONDA.T_NDCRECEIVED.AFOFFTIME
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setAfofftime(BigDecimal afofftime) {
        this.afofftime = afofftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.FACTORYNO
     *
     * @return the value of HONDA.T_NDCRECEIVED.FACTORYNO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public Short getFactoryno() {
        return factoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.FACTORYNO
     *
     * @param factoryno the value for HONDA.T_NDCRECEIVED.FACTORYNO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setFactoryno(Short factoryno) {
        this.factoryno = factoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.KDLOTNO
     *
     * @return the value of HONDA.T_NDCRECEIVED.KDLOTNO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getKdlotno() {
        return kdlotno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.KDLOTNO
     *
     * @param kdlotno the value for HONDA.T_NDCRECEIVED.KDLOTNO
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setKdlotno(String kdlotno) {
        this.kdlotno = kdlotno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONDA.T_NDCRECEIVED.PLANCODE
     *
     * @return the value of HONDA.T_NDCRECEIVED.PLANCODE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public String getPlancode() {
        return plancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONDA.T_NDCRECEIVED.PLANCODE
     *
     * @param plancode the value for HONDA.T_NDCRECEIVED.PLANCODE
     *
     * @mbggenerated Sat Mar 11 16:09:56 ICT 2017
     */
    public void setPlancode(String plancode) {
        this.plancode = plancode;
    }
}